"""init

Revision ID: 928c7f642f28
Revises: 
Create Date: 2026-02-25 19:42:49.043719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '928c7f642f28'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('sprite', sa.String(length=300), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('types', sa.JSON(), nullable=False),
    sa.Column('abilities', sa.JSON(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('moves', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pokemon_id'), 'pokemon', ['id'], unique=False)
    op.create_index(op.f('ix_pokemon_name'), 'pokemon', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokemon_name'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_id'), table_name='pokemon')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
