"""add pokedex fields

Revision ID: f5e157227502
Revises: 928c7f642f28
Create Date: 2026-02-25 20:51:06.720640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f5e157227502"
down_revision: Union[str, Sequence[str], None] = "928c7f642f28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Sonar: evitar duplicação de literais
JSON_EMPTY_ARRAY_DEFAULT = sa.text("'[]'::json")
FALSE_DEFAULT = sa.text("false")


def upgrade() -> None:
    op.add_column("pokemon", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("pokemon", sa.Column("genus", sa.String(length=120), nullable=True))

    # adiciona com default temporário pra não quebrar se existir dado
    op.add_column(
        "pokemon",
        sa.Column("egg_groups", sa.JSON(), nullable=False, server_default=JSON_EMPTY_ARRAY_DEFAULT),
    )
    op.add_column("pokemon", sa.Column("gender_rate", sa.Integer(), nullable=True))
    op.add_column(
        "pokemon",
        sa.Column("evolution_chain", sa.JSON(), nullable=False, server_default=JSON_EMPTY_ARRAY_DEFAULT),
    )
    op.add_column(
        "pokemon",
        sa.Column("weaknesses", sa.JSON(), nullable=False, server_default=JSON_EMPTY_ARRAY_DEFAULT),
    )
    op.add_column(
        "pokemon",
        sa.Column("captured", sa.Boolean(), nullable=False, server_default=FALSE_DEFAULT),
    )

    op.create_index(op.f("ix_pokemon_captured"), "pokemon", ["captured"], unique=False)

    # remove defaults (opcional, deixa o schema mais “limpo”)
    op.alter_column("pokemon", "egg_groups", server_default=None)
    op.alter_column("pokemon", "evolution_chain", server_default=None)
    op.alter_column("pokemon", "weaknesses", server_default=None)
    op.alter_column("pokemon", "captured", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pokemon_captured"), table_name="pokemon")
    op.drop_column("pokemon", "captured")
    op.drop_column("pokemon", "weaknesses")
    op.drop_column("pokemon", "evolution_chain")
    op.drop_column("pokemon", "gender_rate")
    op.drop_column("pokemon", "egg_groups")
    op.drop_column("pokemon", "genus")
    op.drop_column("pokemon", "description")
    # ### end Alembic commands ###